name: signup

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 16 * * *"
jobs:
    start_sign:
        name: start_daily_sign
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: checkout_submodules
              uses: textbook/git-checkout-submodule-action@master
            - uses: actions/setup-node@v2-beta
              with:
                node-version: '14'
            - name: pusacg_sign
              env:
                SITEHOST: "https://www.pusacgn.org/"
                USR: ${{ secrets.USR }}
                PASS: ${{ secrets.PASS }}
              run: |
                npm i 
                npm run sign
